### ISSUE TITLE
网络曲库搜索不了啦

### ISSUE THREAD

**Issue by VarYong** [Mcdull0921/PoorMusic#2]

**Comment by Mcdull0921** [comment]
已更新，但目前未能破解加密方式，只能通过在网页上抓取生成好的值进行硬编码
主要修改为2个地方：
1.cookie
2.secret
可参见该提交[930757](https://github.com/Mcdull0921/PoorMusic/commit/930757aa5ee64d5b5a3d3a0ac99d1d60832db14d)
