### ISSUE TITLE
求发布一个安装包；

### ISSUE THREAD

**Issue by yangteng2013** [Mcdull0921/PoorMusic#3]

**Comment by Mcdull0921** [comment]
绿色版，无须安装，windows7以上应该都能跑，下载地址：https://github.com/Mcdull0921/PoorMusic/releases/download/20231212/PoorMusic-v0.3.4.zip
但目前无法下载vip歌曲，只能当作一个普通音乐播放器使用

**Comment by Mcdull0921** [comment]
最新版已发布，打开即用
https://github.com/Mcdull0921/PoorMusic/releases/download/v0.4.0/PoorMusic-0.4.0.zip
